<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Clearpay\Clearpay\ViewModel\Container\ExpressCheckout\Headless $viewModel */

$viewModel = $block->getViewModel();
$jsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/view/container/express-checkout/cart/headless.js');
$externalJsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/view/container/express-checkout/cart/express-checkout-cart-widget.js');
?>

<script>
    if (typeof clearpayCartId === 'undefined') {
        var clearpayCartId = "<?= /* @noEscape */ $viewModel->getCartId() ?>";
    }
    if (typeof clearpayStoreId === 'undefined') {
        var clearpayStoreId = "<?= /* @noEscape */ $viewModel->getStoreId() ?>";
    }
    if (typeof clearpayLocaleCode === 'undefined') {
        var clearpayLocaleCode = "<?= /* @noEscape */ $viewModel->getCountryCode() ?>";
    }
</script>

<script src="<?= $escaper->escapeUrl($jsUrl) ?>" async></script>
<script src="<?= $escaper->escapeUrl($externalJsUrl) ?>" async></script>

<section id="headless-clearpay-cart-ec" class="headless-clearpay-ec hidden headless-clearpay-cart-ec">
        <div class="clearpay-express-checkout-product-wrapper">
            <button class="clearpay-express-button clearpay-express-button-cart">
                <img src="https://static.afterpay.com/<?= /* @noEscape */ str_replace('_','-',$viewModel->getStoreLocale()) ?>/integration/button/checkout-with-clearpay/white-on-black.svg"
                     alt="<?= /* @noEscape */ __('Checkout with Clearpay') ?>" style="width: 267px;"/>
            </button>
            <div class="hiidden" id="clearpay-button-cart" data-afterpay-entry-point="cart"></div>
        </div>
</section>
