<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Clearpay\Clearpay\ViewModel\Container\ExpressCheckout\Headless $viewModel */

$viewModel = $block->getViewModel();
$utilityJsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/service/utils/wait-for-selector.js');
$jsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/view/container/express-checkout/cart/headless.js');
$externalJsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/view/container/express-checkout/cart/express-checkout-cart-widget.js');

$loadingHtml = '';
// Check if Hyva theme is active
$isHyva = $viewModel->isHyva();
if ($isHyva) {
    $loadingHtml = $block->getChildHtml('loading');
    if (!$loadingHtml) {
        $loadingHtml = $block->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('Clearpay_Clearpay::hyva/ui/loading.phtml')
            ->toHtml();
    }
}
?>

<script>
    if (typeof clearpayCartId === 'undefined') {
        var clearpayCartId = "<?= /* @noEscape */ $viewModel->getCartId() ?>";
    }
    if (typeof clearpayStoreId === 'undefined') {
        var clearpayStoreId = "<?= /* @noEscape */ $viewModel->getStoreId() ?>";
    }
    if (typeof clearpayLocaleCode === 'undefined') {
        var clearpayLocaleCode = "<?= /* @noEscape */ $viewModel->getCountryCode() ?>";
    }
</script>

<script src="<?= $escaper->escapeUrl($utilityJsUrl) ?>"></script>
<script src="<?= $escaper->escapeUrl($jsUrl) ?>" async></script>
<script src="<?= $escaper->escapeUrl($externalJsUrl) ?>" async></script>
<?php if ($isHyva): ?>
<script>
    'use strict';

    function initHyvaCartLoaderComponent() {
        return {
            isLoading: false,
            startLoaderCart() {
                this.isLoading = true;
            },
            stopLoaderCart() {
                this.isLoading = false;
            }
        }
    }
</script>
<?php endif; ?>

<section <?= $isHyva ? 'x-data="initHyvaCartLoaderComponent()" @start-loader-cart.window="startLoaderCart()" @processStop.window="stopLoaderCart()"' : '' ?>
         id="headless-clearpay-cart-ec" class="headless-clearpay-ec hidden headless-clearpay-cart-ec">
    <?php if ($isHyva): ?>
    <div x-show="isLoading">
        <?= /* @noEscape */ $loadingHtml ?>
    </div>
    <?php endif; ?>
    <div class="clearpay-express-checkout-product-wrapper">
            <button class="clearpay-express-button clearpay-express-button-cart">
                <img src="<?= $escaper->escapeUrl($viewModel->getImageurl()) ?>"
                     alt="<?= /* @noEscape */ __('Checkout with Clearpay') ?>" style="width: 267px;"/>
            </button>
            <div class="hidden" id="clearpay-button-cart" data-afterpay-entry-point="cart"></div>
        </div>
</section>
