<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Clearpay\Clearpay\ViewModel\Container\ExpressCheckout\Headless $viewModel */

$viewModel = $block->getViewModel();
$utilityJsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/service/utils/wait-for-selector.js');
$jsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/view/container/express-checkout/minicart/headless.js');
$externalJsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/view/container/express-checkout/minicart/express-checkout-minicart-widget.js');

$loadingHtml = '';
// Check if Hyva theme is active
$isHyva = $viewModel->isHyva();
if ($isHyva) {
    $loadingHtml = $block->getChildHtml('loading');
    if (!$loadingHtml) {
        $loadingHtml = $block->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('Clearpay_Clearpay::hyva/ui/loading.phtml')
            ->toHtml();
    }
}
?>

<script>
    if (typeof clearpayLocaleCode === 'undefined') {
        var clearpayLocaleCode = "<?= /* @noEscape */ $viewModel->getCountryCode() ?>";
    }
</script>

<script src="<?= $escaper->escapeUrl($utilityJsUrl) ?>"></script>
<script src="<?= $escaper->escapeUrl($jsUrl) ?>" async></script>
<script src="<?= $escaper->escapeUrl($externalJsUrl) ?>" async></script>
<?php if ($isHyva): ?>
<script>
    'use strict';

    function initHyvaMinicartLoaderComponent() {
        return {
            isLoading: false,
            startLoaderMinicart() {
                this.isLoading = true;
            },
            stopLoaderMinicart() {
                this.isLoading = false;
            }
        }
    }
</script>
<?php endif; ?>
<section <?= $isHyva ? 'x-data="initHyvaMinicartLoaderComponent()" @start-loader-minicart.window="startLoaderMinicart()" @processStop.window="stopLoaderMinicart()"' : '' ?> id="headless-clearpay-minicart-ec"
         class="headless-clearpay-ec hidden headless-clearpay-minicart-ec">
    <?php if ($isHyva): ?>
    <div x-show="isLoading">
        <?= /* @noEscape */ $loadingHtml ?>
    </div>
    <?php endif; ?>
    <div class="clearpay-express-checkout-product-wrapper">
        <button class="clearpay-express-button clearpay-express-button-minicart clearpay-minicart-spacer">
            <img src="<?= $escaper->escapeUrl($viewModel->getImageurl()) ?>"
                 alt="<?= /* @noEscape */
                 __('Checkout with Clearpay') ?>" style="width: 100%;"/>
        </button>
        <div class="hidden" id="clearpay-button-minicart" data-afterpay-entry-point="mini-cart"></div>
    </div>
</section>
