<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2016-2020 Clearpay https://www.clearpay.co.uk
 */
$cartDisplayMode = (int) $block->isDisplayOnCartPage();
$data_amount = $block->getFinalAmount();
if ($block->isPaymentMethodActive() && $cartDisplayMode != \Clearpay\Clearpay\Model\Config\Source\CartMode::DISABLED && $block->canUseCurrency() && $data_amount>0) {
    $clearpay_eligible = "true";
    if (($block->canShow() === false)) {
        $clearpay_eligible = "false";
    }
      
    $min_limit=$block->getMinOrderLimit();
    $max_limit=$block->getMaxOrderLimit();
    $show_lower_limit="true";
    if((float)$min_limit<1){
        $show_lower_limit="false";
    }
?>
<script src="<?= $block->escapeUrl($block->getClearpayECJsUrl());?>" async></script>
<script src="<?= $block->escapeUrl($block->getClearpayJsLibUrl());?>"
	data-min="<?= /* @noEscape */ $min_limit; ?>"
	data-max="<?= /* @noEscape */ $max_limit; ?>" async></script>
<?php
    $store_currency = $block->getCurrentCurrency();
    $data_locale = $block->getCurrentLocale();

    $enable_cbt = $this->helper('Clearpay\Clearpay\Helper\Data')->getConfig('payment/clearpaypayovertime/enable_cbt');
    $data_enable_cbt = ! empty($enable_cbt) ? "true" : "false";
?>
 <afterpay-placement
    	data-locale="<?= /* @noEscape */  $data_locale;?>"
    	data-currency="<?= /* @noEscape */ $store_currency;?>"
    	data-amount="<?= /* @noEscape */ $data_amount; ?>"    	
    	data-cbt-enabled="<?= /* @noEscape */ $data_enable_cbt;?>"
    	data-show-lower-limit="<?= /* @noEscape */  $show_lower_limit;?>"
    	data-cart-is-eligible="<?= /* @noEscape */ $clearpay_eligible;?>"
    	data-intro-text="Pay in"></afterpay-placement>
<?php
if ($data_amount >= $min_limit && $data_amount <= $max_limit && $clearpay_eligible != "false" ) {
    if ($cartDisplayMode == \Clearpay\Clearpay\Model\Config\Source\CartMode::EXPRESS_CHECKOUT) {
?>	
<button id="clearpay-express-button" data-afterpay-entry-point="cart" class="clearpay primary express-button">
	<img id="clearpay-express-start"
		src="https://static.afterpay.com/button/checkout-with-clearpay/white-on-black.svg"
		alt="Checkout with Clearpay" />
</button>
<?php }else{?>    <!--    Button buy now-->
	    <button type="button" data-role="proceed-to-checkout" onclick="window.location.href='<?php echo $block->getUrl('checkout', ['_secure' => true]);?>'" title="<?php echo __('Buy now, pay later') ?>" class="clearpay primary btn-clearpay-checkout">
	        <img src="https://static.afterpay.com/integration/logo-clearpay-white-162x31.png" alt="<?php echo __('Buy now, pay later'); ?>" srcset="https://static.afterpay.com/integration/logo-clearpay-white-162x31.png 1x,https://static.afterpay.com/integration/logo-clearpay-white-162x31@2x.png 2x,https://static.afterpay.com/integration/logo-clearpay-white-162x31@3x.png 3x" height="31"/>
	    </button>
<?php }
    }
} ?>
