<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2021 Clearpay https://www.clearpay.com
 */
if(($block->isPaymentMethodActive()  &&  $block->isDisplayOnCartPage()  && $block->canUseCurrency())){
    $clearpay_eligible = "true";
    if (($block->canShow() === false)) {
        $clearpay_eligible = "false";
    }
      
    $min_limit=$block->getMinOrderLimit();
    $max_limit=$block->getMaxOrderLimit();
    $show_lower_limit="true";
    if((float)$min_limit<1){
        $show_lower_limit="false";
    }
 ?> <script
    	src="<?= $block->escapeUrl($block->getClearpayJsLibUrl());?>"
    	data-min="<?= /* @noEscape */ $min_limit; ?>"
    	data-max="<?= /* @noEscape */ $max_limit; ?>" async></script>
 <?php 
    $store_currency = $block->getCurrentCurrency();
    $data_locale = $block->getCurrentLocale();
    $data_amount = $block->getFinalAmount();
    //$enable_cbt = $this->helper('Clearpay\ClearpayEurope\Helper\Data')->getConfig('payment/clearpayeupayovertime/enable_cbt');
    //$data_enable_cbt = ! empty($enable_cbt) ? "true" : "false";
?>
 <afterpay-placement
    	data-locale="<?= /* @noEscape */  $data_locale;?>"
    	data-currency="<?= /* @noEscape */ $store_currency;?>"
    	data-amount="<?= /* @noEscape */ $data_amount; ?>"
    	data-show-lower-limit="<?= /* @noEscape */  $show_lower_limit;?>"
    	data-cart-is-eligible="<?= /* @noEscape */ $clearpay_eligible;?>"
 ></afterpay-placement>
<?php

} ?>
