<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2016-2019 Clearpay https://www.clearpay.co.uk
 */
?>
<?php if ($block->canShow()) : ?>
	    <div class='payment-method-note clearpay-checkout-note' style='text-align: left; margin-bottom: 1.5rem; font-size: 13px;'><h3 style="font-size: 1.5rem"><span style="color: #00a4e4;">
	    <?php echo $block->getCartPageText(); ?>
	    </div>

	    <!--    Button buy now-->
	    <button type="button" data-role="proceed-to-checkout" onclick="window.location.href='<?php echo $block->getUrl('checkout', ['_secure' => true]);?>'" title="<?php echo __('Buy now, pay later') ?>" class="action primary btn-clearpay-checkout">
	        <img src="<?php echo $block->getViewFileUrl('Clearpay_Clearpay::images/clearpay_logo_white.png'); ?>" alt="<?php echo __('Buy now, pay later'); ?>" />
	    </button>
<?php endif; ?>
