<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2016-2021 Clearpay https://www.clearpay.co.uk
 */
if($block->isPaymentMethodActive() ){
$displayExpress = "";
if (!$block->canUseCurrency() || !$block->canShow() || !$block->isWithinLimits()) {
    $displayExpress = 'style="display:none;"';
}

?>
<script src="<?= $block->escapeUrl($block->getClearpayECJsUrl());?>" async></script>
<button id="clearpay-minicart-express-button" data-afterpay-entry-point="mini-cart" class="clearpay primary express-button minicart" <?php echo $displayExpress?>>
    <img id="clearpay-express-start"
         src="https://static.afterpay.com/button/checkout-with-clearpay/white-on-black.svg"
         alt="Checkout with Clearpay" />
</button>
<script type="text/x-magento-init">
{
    "*": {
		"Clearpay_Clearpay/js/view/cart/clearpay-minicart": {
		     "clearpayConfig":<?php echo $block->getClearpayConfigs(); ?>
		}
	}
}
</script>
<script type="text/x-magento-init">
        {
            "*": {
                "Clearpay_Clearpay/js/view/express/clearpay-express": {
                    "clearpayConfig":<?php echo $block->getClearpayConfigs(); ?>,
                    "isMinicartVirtual":"<?php echo $block->isQuoteVirtual(); ?>"
                }
            }
        }
</script>
<?php } ?>
