<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2021 Clearpay https://www.clearpay.com
 */
$store_base_currency = $this->helper('Clearpay\ClearpayEurope\Helper\Data')->getConfig('currency/options/default');
?>
<div id="clearpayeu-modal-popup" style="display:none">
    <a href="https://www.clearpay.co.uk/terms" target="_blank">
        <img class="clearpay-modal-image" alt="Clearpay"/>
    </a>
</div>
<script>
	require(
        [
            'jquery',
			'Magento_Ui/js/modal/modal'
		],
        function(
            $,
			modal
        ){
			var storeCurrency="<?php echo $store_base_currency;?>";
			var width=$(window).width();
			
			var options = {
                responsive: false,
                innerScroll: false,
                modalClass: 'clearpayeu-learn-more'
            };
            // register poup
            var popup = modal(options, $('#clearpayeu-modal-popup'));
			
			if(width > 640){
				$("#clearpayeu-modal-popup .clearpay-modal-image").attr({src:"https://static.afterpay.com/clearpay-lightbox-desktop.png",srcset:"https://static.afterpay.com/clearpay-lightbox-desktop.png 1x,https://static.afterpay.com/clearpay-lightbox-desktop@2x.png 2x"});
			}
			else{
				$("#clearpayeu-modal-popup .clearpay-modal-image").attr({src:"https://static.afterpay.com/clearpay-lightbox-mobile.png",srcset:"https://static.afterpay.com/clearpay-lightbox-mobile.png 1x,https://static.afterpay.com/clearpay-lightbox-mobile@2x.png 2x"});
			}

            // register the click to be popup
            $( ".clearpay-modal-popup-trigger" ).on( "click", function() {
                $('#clearpay-modal-popup').show();
                $('#clearpay-modal-popup').modal('openModal');
            });
		}
	);
</script>

