<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2016-2019 Clearpay https://www.clearpay.co.uk
 */
?>
<?php 
$product_type=$block->getTypeOfProduct();
$display="";
//Check currency and if Clearpay is enabled
if($block->canShow() && $product_type!="grouped") : 
if(!$block->isProductEligible()){
	$display="display:none";
}
?>
	<div maxLimit="<?php echo $block->getMaxOrderLimit(); ?>" minLimit="<?php echo $block->getMinOrderLimit(); ?>" product_type="<?php echo $product_type; ?>" style="position: relative; font-style: italic; line-height: 1.4;margin-bottom:5px;<?php echo $display;?>" class="clearpay-installments clearpay-installments-amount">
	<?php $assets_product_page = $block->getInstalmentText(); 
	echo $assets_product_page['snippet1'];
	?>
	<span class="clearpay_instalment_price"><?php echo $block->getInstallmentsAmount(); ?></span>
	<br/>
	<?php
	$assets_product_snippet2  = $assets_product_page['snippet2'];
	$assets_product_snippet2 = str_replace(array('[modal-href]'), 
	                    array('javascript:void(0)'), $assets_product_snippet2);
	echo $assets_product_snippet2;
	?>
	</div>
<?php endif; ?>
