<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2016-2021 Clearpay https://www.clearpay.co.uk
 */

/** @var \Clearpay\Clearpay\Block\Catalog\Installments $block */
$product_type = $block->getTypeOfProduct();
$data_amount = $block->getFinalAmount();

if ($block->isPaymentMethodActive() && $product_type != "grouped" && $block->canUseCurrency() && $data_amount > 0) {
    $clearpay_eligible = "true";
    if (($block->canShow() === false)) {
        $clearpay_eligible = "false";
    }
    $min_limit = $block->getMinOrderLimit();
    $show_lower_limit = "true";
    if ((float)$min_limit < 1) {
        $show_lower_limit = "false";
    }
    $max_limit = $block->getMaxOrderLimit();
    $productPriceFormat = $this->helper('Magento\Tax\Helper\Data')->getPriceFormat($block->getStore());
    $priceFormat = $block->getJsonDecode($productPriceFormat);
    $isECenabled=$block->isDisplayEConProductPage();
    $isDisplay=(int)$block->isDisplayOnProductPage();
    if (!$block->isDisplayECOnMiniCart()) {
        ?>
        <script src="<?= $block->escapeUrl($block->getClearpayECJsUrl()); ?>" async></script>
    <?php }
    if ($block->isDisplayOnProductPage()) { ?>
        <script
            src="<?= $block->escapeUrl($block->getClearpayJsLibUrl()); ?>"
            data-min="<?= /* @noEscape */ $min_limit; ?>"
            data-max="<?= /* @noEscape */ $max_limit; ?>" async></script>
        <?php
        $store_currency = $block->getCurrentCurrency();
        $data_locale = $block->getCurrentLocale();

        $enable_cbt = $this->helper('Clearpay\Clearpay\Helper\Data')->getConfig('payment/clearpaypayovertime/enable_cbt');
        $data_enable_cbt = !empty($enable_cbt) ? "true" : "false";
        ?>
        <afterpay-placement
            data-locale="<?= /* @noEscape */ $data_locale; ?>"
            data-currency="<?= /* @noEscape */ $store_currency; ?>"
            data-amount="<?= /* @noEscape */ $data_amount; ?>"
            data-is-eligible="<?= /* @noEscape */ $clearpay_eligible; ?>"
            data-cbt-enabled="<?= /* @noEscape */ $data_enable_cbt; ?>"
            data-show-lower-limit="<?= /* @noEscape */ $show_lower_limit; ?>"
            data-decimal-separator="<?= /* @noEscape */ $priceFormat["decimalSymbol"]; ?>"
            data-thousands-separator="<?= /* @noEscape */ $priceFormat["groupSymbol"]; ?>"></afterpay-placement>

        <?php
    }
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Clearpay_Clearpay/js/view/product/clearpay-products": {
                    "clearpayConfig":<?php echo $block->getClearpayConfigs(); ?>,
                    "productPriceFormat":<?php echo $productPriceFormat; ?>,
                    "isECenabled":<?php echo $isECenabled;?>,
                    "isDisplay":<?php echo $isDisplay;?>,
                    "isProductVirtual":"<?= $block->getProduct()->isVirtual(); ?>"
                }
            }
        }
    </script>

   <?php if ($block->isDisplayEConProductPage() && $clearpay_eligible != "false" && !$block->isProductOutOfStock()) { ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Clearpay_Clearpay/js/view/express/clearpay-express": {
                    "clearpayConfig":<?php echo $block->getClearpayConfigs(); ?>,
                    "isProductVirtual":"<?php echo $block->isProductVirtual(); ?>",
                    "productType":"<?php echo $product_type; ?>"
                }
            }
        }
        </script>
        <button id="clearpay-pdp-express-button" data-afterpay-entry-point="product-page" class="clearpay primary express-button" style="display: none;">
            <img id="clearpay-express-start"
                 src="https://static.afterpay.com/button/checkout-with-clearpay/white-on-black.svg"
                 alt="Checkout with Clearpay"/>
        </button>
    <?php }
} ?>
