<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2016-2020 Clearpay https://www.clearpay.co.uk
 */
$product_type = $block->getTypeOfProduct();
if(($block->isPaymentMethodActive()  && $block->isDisplayOnProductPage() && $product_type != "grouped" && $block->canUseCurrency())){

    $clearpay_eligible = "true";
    if (($block->canShow() === false)) {
        $clearpay_eligible = "false";
    }
    $min_limit=$block->getMinOrderLimit();
    $show_lower_limit="true";
    if((float)$min_limit<1){
        $show_lower_limit="false";
    }
    ?>
    <script
    	src="<?= $block->escapeUrl($block->getClearpayJsLibUrl());?>"
    	data-min="<?= /* @noEscape */ $min_limit; ?>"
    	data-max="<?= /* @noEscape */ $block->getMaxOrderLimit(); ?>" async></script>
    <?php
    $store_currency = $block->getCurrentCurrency();
    $data_locale = $block->getCurrentLocale();
    $data_amount = $block->getFinalAmount();
    $enable_cbt = $this->helper('Clearpay\Clearpay\Helper\Data')->getConfig('payment/clearpaypayovertime/enable_cbt');
    $data_enable_cbt = ! empty($enable_cbt) ? "true" : "false";
    ?>
    <afterpay-placement
    	data-locale="<?= /* @noEscape */  $data_locale;?>"
    	data-currency="<?= /* @noEscape */ $store_currency;?>"
    	data-amount="<?= /* @noEscape */ $data_amount; ?>"
    	data-is-eligible="<?= /* @noEscape */ $clearpay_eligible;?>"
    	data-cbt-enabled="<?= /* @noEscape */ $data_enable_cbt;?>"
    	data-show-lower-limit="<?= /* @noEscape */  $show_lower_limit;?>"></afterpay-placement>
<?php
}
?>
