<?php
declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */

?>
<div id="clearpay-hyva-template"
     class="w-full pl-8 mt-4"
     data-terms-default="<?= $escaper->escapeHtmlAttr(__('You will be redirected to the Clearpay website when you proceed to checkout.')) ?>">
    <div id="clearpay-payment-schedule-container"></div>
    <div id="clearpay-terms-container" style="display:none;text-align:center">
        <p>
            <span id="clearpay-terms-text"></span>
            <a id="clearpay-terms-link" href="#" target="_blank" class="underline text-primary hover:text-primary-darker">
                <?= $escaper->escapeHtml(__('Terms & Conditions')) ?>
            </a>
        </p>
    </div>
    <div class="flex justify-center mt-4">
        <div id="clearpay-hyva-checkout" class="btn btn-primary cursor-pointer">
            <?= $escaper->escapeHtml(__('Continue to Clearpay')) ?>
        </div>
    </div>
</div>
