<?php
/** @var Clearpay\Clearpay\Block\Cta\CartHeadless $block */
/** @var Clearpay\Clearpay\ViewModel\Container\Cta\Headless $viewModel */
$viewModel = $block->getViewModel();
$utilityJsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/service/utils/wait-for-selector.js');
$jsUrl = $block->getViewFileUrl('Clearpay_Clearpay::js/view/container/cta/cart/headless.js');
?>
<script>
    if (typeof clearpayCartId === 'undefined') {
        var clearpayCartId = "<?= /* @noEscape */ $viewModel->getCartId() ?>";
    }
    if (typeof clearpayStoreId === 'undefined') {
        var clearpayStoreId = "<?= /* @noEscape */ $viewModel->getStoreId() ?>";
    }
    if (typeof clearpayCurrency === 'undefined') {
        window.clearpayCurrency = "<?= /* @noEscape */ $viewModel->getCurrency() ?>";
    }
</script>
<script src="<?= /** @noEscape */ $utilityJsUrl ?>"></script>
<script src="<?= /** @noEscape */ $jsUrl ?>" async></script>
