<?php
/**
 * Magento 2 extensions for Clearpay Payment
 *
 * @author Clearpay
 * @copyright 2016-2019 Clearpay https://www.clearpay.co.uk
 */
?>
<?php 
//Check currency and if Clearpay is enabled
$product_type=$block->getTypeOfProduct();
if($block->canShow()) : ?>
	<div maxLimit="<?php echo $block->getMaxOrderLimit(); ?>" minLimit="<?php echo $block->getMinOrderLimit(); ?>" style="position: relative; font-style: italic; line-height: 1.4;margin-bottom:5px;<?php echo $block->isProductEligible(); ?>" product_type="<?php echo $product_type; ?>" class="clearpay-installments clearpay-installments-amount">
	<?php $assets_product_page = $block->getInstalmentText(); 
	echo $assets_product_page['snippet1'];
	?>
	<span class="clearpay_instalment_price"><?php echo $block->getInstallmentsAmount(); ?></span>
	<br/>
	<?php
	$assets_product_snippet2  = $assets_product_page['snippet2'];
	$assets_product_snippet2 = str_replace(array('[modal-href]'), 
	                    array('javascript:void(0)'), $assets_product_snippet2);
	echo $assets_product_snippet2;
	?>
	</div>
<?php endif; ?>
